### ISSUE TITLE
Header section: Font style used for 'Get in Touch Today' should be Myriad Pro per design provided.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/GKR-Transport#1]
Font style used in front end is Droid Sans, san- serif.
Applicable to "Get in Touch Today" of the lead-ins section.

![image](https://cloud.githubusercontent.com/assets/11186313/6796347/72137d36-d22c-11e4-942a-ab63d323f310.png)

**Comment by arielcebudigital** [comment]
Myriad Pro(Black list) 
Droid Sans - suggested by Doyle, and for this font only normal and bold are available.
