### ISSUE TITLE
Header section: Font weight for 'Get in Touch Today' should be semi bold as per design.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/GKR-Transport#2]
Font weight used in front end is normal.

![image](https://cloud.githubusercontent.com/assets/11186313/6796361/a3b21956-d22c-11e4-9ad1-f95e6f1cdf46.png)

**Comment by doylesee** [comment]
Input reason why this is invalid.

**Comment by arielcebudigital** [comment]
Invalid, Myriad Pro is a blacklist font.
