### ISSUE TITLE
Online Quote form:  Shouldn't we be extracting the same fields from the existing site as stated in the design brief?

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/GKR-Transport#29]
![image](https://cloud.githubusercontent.com/assets/11186313/6799046/a2d445c4-d24d-11e4-93b8-7fbf5235c783.png)

**Comment by arielcebudigital** [comment]
You mean the (Item Description and Other Information that using textarea)?, if we follow this our design will be change. will be that okay?
