### ISSUE TITLE
Banner section: Missing 2px section border, color #ecedee at the bottom of the banner image.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/GKR-Transport#3]
![image](https://cloud.githubusercontent.com/assets/11186313/6796399/75402238-d22d-11e4-8976-dbe2e3ca3362.png)

**Comment by arielcebudigital** [comment]
actually its not border-color, try to check in the PSD

**Comment by arielcebudigital** [comment]
I put invalid because its not border-color.

**Comment by roseliesromeo** [comment]
Added
