### ISSUE TITLE
Header section: Sub menu won't show upon clicking the drop down arrow.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/GKR-Transport#35]
iTouch 5

**Comment by arielcebudigital** [comment]
Please provide screenshot,  we cannot replicate the issue because we don't have the actual device.

**Comment by arielcebudigital** [comment]
menu -3rd level is the max

**Comment by roseliesromeo** [comment]
![image](https://cloud.githubusercontent.com/assets/11186313/6861567/0a723e62-d473-11e4-9999-378d5c948709.png)
