### ISSUE TITLE
Contact Us page:  Font effect used for the address is inconsistent.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/GKR-Transport#52]
![image](https://cloud.githubusercontent.com/assets/11186313/6863547/f336010e-d48e-11e4-8a39-9c537a6addee.png)

**Comment by arielcebudigital** [comment]
:-) You can change it anytime, its not the effect that i used..it's in the business details..

**Comment by arielcebudigital** [comment]
base on http://gkrtransport.com.au/contact.asp,

**Comment by roseliesromeo** [comment]
Oh, mostly we don't change info at back end. We only remove or replace it with testing data but place the orig data back after testing.

Existing site is totally different from the current one.  Remember, there is FAQ in the existing site but none in this one.

And lastly, All caps, small caps etc. are all font effects.
![image](https://cloud.githubusercontent.com/assets/11186313/6865617/7cd00480-d4aa-11e4-9de6-86cbd7abade5.png)

**Comment by roseliesromeo** [comment]
Not fixed for the other locations.

**Comment by arielcebudigital** [comment]
Hi rosalle

Gi tuyo na nako sa taas kai ang collapse gud kai naa jud sa title, same na sa sidebar nila nga dile consistent sa design…
