### ISSUE TITLE
FAQ page:  Layout of the arrow and the line dividing each FAQ item when content is expanded doesn't match the design provided.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/GKR-Transport#55]
![image](https://cloud.githubusercontent.com/assets/11186313/6893743/0e1256f6-d702-11e4-9d45-9cdc8dd2619a.png)

**Comment by arielcebudigital** [comment]
I already ask leaman about this issue, He told me that what i did is the right UX for the design.:-)
