### ISSUE TITLE
Lead-ins section: Distorted layout of the lead-ins.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/GKR-Transport#65]
![image](https://cloud.githubusercontent.com/assets/11186313/7039388/d48dfc5c-ddf3-11e4-9df9-69bc01916589.png)

**Comment by arielcebudigital** [comment]
try to clear cache 
![ie-7-gkr](https://cloud.githubusercontent.com/assets/11186408/7058747/c3ca5894-de1a-11e4-86a7-808913390a8d.png)

**Comment by roseliesromeo** [comment]
How come the video in the banner is now removed?  It could have caused it.

**Comment by arielcebudigital** [comment]
i did not change anything in the video, since the only update i made this morning is the quote form

**Comment by roseliesromeo** [comment]
Then, how come it is removed now?  
![image](https://cloud.githubusercontent.com/assets/11186313/7059240/443ed6e6-dea0-11e4-9b17-76812de91356.png)

**Comment by arielcebudigital** [comment]
I will investigate that one later, since the only update i made is quote form..

**Comment by roseliesromeo** [comment]
I will verify once the video is up.

**Comment by roseliesromeo** [comment]
Layout of the lead-ins will be distorted after clicking the video button.
IE7
![image](https://cloud.githubusercontent.com/assets/11186313/7130759/437ba854-e2a8-11e4-9581-cc207ec0b61e.png)

**Comment by roseliesromeo** [comment]
Not fixed for the home page lead-ins
