### ISSUE TITLE
Header section: Font style used for the main menu is Myriad Pro per design PSD.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/GKR-Transport#7]
Current font style used in front end is Droid Sans, san serif

![image](https://cloud.githubusercontent.com/assets/11186313/6796617/780f5818-d231-11e4-8534-46d5351de241.png)

**Comment by arielcebudigital** [comment]
Myriad Pro(Black list) 
Droid Sans - suggested by Doyle, and for this font only normal and bold are available.
